
modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
modId="phishcraft" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Phishcraft" #mandatory
logoFile="phishcraft.png" #optional
credits="Thanks to all the phishermen out there" #optional
authors="" #optional

description='''
Phishing at its finest
'''

[[dependencies.phishcraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[44,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.phishcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
